apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab8
  template:
    metadata:
      labels:
        app: lab8
    spec:
      containers:
        - name: lab8
          image: nginx:latest
          ports:
            - containerPort: 80
