apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab8
  template:
    metadata:
      labels:
        app: lab8
    spec:
      containers:
        - name: app
          image: ghcr.io/${{ github.repository }}:sha-${GITHUB_SHA}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 5
