name: CI Pipeline
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: app
        run: npm install

      - name: Lint
        working-directory: app
        run: npm run lint

      - name: Test
        working-directory: app
        run: npm test

  deploy-staging:
    name: Deploy to Staging (AWS EKS)
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::788670788114:role/GitHubActionsEKSDeployRole
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name hireme-eks-cluster --region us-east-1

      - name: Deploy to EKS
        run: kubectl apply -f k8s/

