name: CI — Lint & Test

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/01-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - '.github/workflows/01-ci.yml'

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  node-tests:
    name: Node ${{ matrix.node }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
        os: [ubuntu-latest]
    env:
      CI: true
      WD: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: ${{ env.WD }}/package-lock.json
      - run: npm ci --ignore-scripts
        working-directory: ${{ env.WD }}
      - run: npm run lint
        working-directory: ${{ env.WD }}
      - run: npm test -- --test-reporter=spec
        working-directory: ${{ env.WD }}
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs-node${{ matrix.node }}-${{ matrix.os }}
          path: ${{ env.WD }}/
          if-no-files-found: ignore
          retention-days: 7
      - if: always()
        run: |
          echo "### CI — Lint & Test" >> $GITHUB_STEP_SUMMARY
          echo "- Node: ${{ matrix.node }}" >> $GITHUB_STEP_SUMMARY
          echo "- OS:   ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY

  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
