name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        working-directory: app
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        working-directory: app
        run: npm test

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  deploy-staging:
    name: Deploy to Staging
    needs: [build, test, security]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up kubectl for kind
        run: |
          kind create cluster --name staging
          kubectl cluster-info
      - name: Deploy to staging
        run: kubectl apply -f k8s/

  deploy-aws:
    name: Deploy to AWS EKS
    needs: [build, test, security]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::788670788114:role/GitHubActionsEKSDeployRole
          aws-region: us-east-1 # change if needed

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name hireme-eks-cluster --region us-east-1

      - name: Deploy to AWS
        run: kubectl apply -f k8s/
