name: Security — Secrets & CodeQL

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write   # needed for SARIF uploads
  actions: read

jobs:
  secrets-gitleaks:
    name: Secrets — Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2

  secrets-trufflehog:
    name: Secrets — TruffleHog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trufflesecurity/trufflehog@main
        with:
          path: .
          json: true
          fail: true

  codeql:
    name: SAST — CodeQL (JavaScript)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild (for compiled langs; harmless for JS)
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
