name: Security — Secrets & CodeQL

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  secrets-trufflehog:
    name: Secrets — TruffleHog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # use a valid tag; v2 is stable. You can also use @main.
      - uses: trufflesecurity/trufflehog@v2
        with:
          path: .
          json: true
          fail: true

  codeql:
    name: SAST — CodeQL (JavaScript)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3
