name: Security — Secrets & CodeQL

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          json: true
          fail: true

  codeql:
    uses: github/codeql-action/.github/workflows/codeql.yml@v3
    with:
      languages: javascript

