name: Security — Secrets & CodeQL

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "0 3 * * *"  # daily sweep

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  secrets-trufflehog:
    name: Secrets — TruffleHog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Pin to a known working tag; avoids "version not found"
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.63.8
        with:
          path: .
          json: true
          entropy: true
          regex: true
          fail: true

  codeql:
    name: SAST — CodeQL (JavaScript)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Analyze
        uses: github/codeql-action/analyze@v3

