name: Build • SBOM • Scan • Sign

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write
  security-events: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker build -t $REGISTRY/$IMAGE_NAME:sha-${GITHUB_SHA} .

      - uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          artifact-name: sbom-spdx.json
          format: spdx-json

      - run: docker push $REGISTRY/$IMAGE_NAME:sha-${GITHUB_SHA}

      - uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.0.0
        with:
          image: ghcr.io/${{ github.repository }}
          digest: ${{ steps.build.outputs.digest }}

      - uses: sigstore/cosign-installer@v3
      - run: |
          COSIGN_EXPERIMENTAL=true cosign sign $REGISTRY/$IMAGE_NAME:sha-${GITHUB_SHA}

  scan:
    needs: build
    uses: ./.github/workflows/reusable-scan-image.yml
    with:
      image: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
