name: build-push-sign

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Compute lowercase repo and image ref once
      - name: Compute image ref
        id: img
        run: |
          REPO_LC="${GITHUB_REPOSITORY,,}"
          echo "REPO_LC=$REPO_LC" >> $GITHUB_ENV
          echo "IMAGE_REF=ghcr.io/${REPO_LC}:sha-${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t "$IMAGE_REF" .

      - name: Push image
        run: docker push "$IMAGE_REF"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign image (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --yes "$IMAGE_REF"
