name: build-push-sign

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Lowercase owner/repo and compute image ref once
      - name: Compute image ref (lowercase)
        id: img
        run: |
          REPO_LC="${GITHUB_REPOSITORY,,}"
          IMAGE_REF="${REGISTRY}/${REPO_LC}:sha-${GITHUB_SHA}"
          echo "REPO_LC=$REPO_LC" >> $GITHUB_ENV
          echo "IMAGE_REF=$IMAGE_REF" >> $GITHUB_ENV
          echo "$IMAGE_REF" > image-ref.txt
        env:
          REGISTRY: ${{ env.REGISTRY }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t "$IMAGE_REF" .

      - name: Push image
        run: docker push "$IMAGE_REF"

      - name: Upload image ref artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-ref
          path: image-ref.txt
          if-no-files-found: error

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign image (keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --yes "$IMAGE_REF"
