name: SBOM & Trivy Scan

on:
  workflow_run:
    workflows: ["build-push-sign"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cloud-automation-portfolio/github-actions-pipelines

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: read

    steps:
      - name: Pull image from GHCR
        run: |
          IMAGE=$REGISTRY/${IMAGE_NAME}:sha-${{ github.event.workflow_run.head_sha }}
          docker pull $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Run Syft SBOM (SPDX)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE }}
          output-file: sbom-spdx.json

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          format: sarif
          output: trivy.sarif

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-spdx
          path: sbom-spdx.json

      - name: Upload SARIF to security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy.sarif
