name: SBOM & Trivy Scan

on:
  workflow_run:
    workflows: [ "build-push-sign" ]
    types: [ completed ]

jobs:
  scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write

    steps:
      - name: Download image ref from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: image-ref
          path: .
      - name: Load IMAGE_REF
        id: load
        run: |
          IMAGE_REF="$(cat image-ref.txt)"
          echo "IMAGE_REF=$IMAGE_REF" >> $GITHUB_ENV
          echo "Using image: $IMAGE_REF"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from GHCR
        run: docker pull "$IMAGE_REF"

      # ---- SBOM (Syft) ----
      - name: Generate SBOM (SPDX) with Syft
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_REF }}
          format: spdx-json
          output-file: sbom-spdx.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx.json
          path: sbom-spdx.json

      # ---- Trivy ----
      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_REF }}
          format: sarif
          output: trivy.sarif
          severity: HIGH,CRITICAL
          exit-code: 0

      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
