name: SBOM & Trivy Scan

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  sbom-trivy:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/<OWNER>/<REPO>:sha-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image from GHCR
        run: docker pull $IMAGE

      # ----- SBOM (Syft) -----
      - name: Run Syft (SBOM SPDX)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE }}
          format: spdx-json
          output-file: sbom-spdx.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx
          path: sbom-spdx.json

      # ----- Trivy -----
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: sarif
          output: trivy.sarif
          severity: HIGH,CRITICAL
          exit-code: 0

      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy.sarif
