name: Deploy — kind (no-cloud smoke)

on:
  pull_request:
    paths:
      - 'k8s/**'
      - 'app/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  kind-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Create kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: lab8
          wait: 120s

      - name: Set image to current commit + apply
        run: |
          kubectl create ns lab8 || true
          IMG="ghcr.io/${{ github.repository }}:sha-${{ github.sha }}"
          # Replace image in deployment.yaml on the fly and apply
          sed -e "s|ghcr.io/.\\+|$IMG|g" k8s/deployment.yaml | kubectl -n lab8 apply -f -
          kubectl -n lab8 apply -f k8s/service.yaml

      - name: Wait for rollout
        run: kubectl -n lab8 rollout status deploy/lab8 --timeout=90s

      - name: Smoke test
        run: |
          kubectl -n lab8 port-forward svc/lab8 8080:80 &
          sleep 3
          curl -fsS http://localhost:8080/ | head -n1

      - name: Summary
        run: |
          echo "### kind deploy OK" >> $GITHUB_STEP_SUMMARY
          kubectl -n lab8 get pods -o wide >> $GITHUB_STEP_SUMMARY
          kubectl -n lab8 get svc lab8 -o wide >> $GITHUB_STEP_SUMMARY
